### PR TITLE
Type hint interface

### PR DESCRIPTION
**Pull request by hannesvdvreken**
### Changed
- Type hint interface instead of concretion

### CODE REVIEW

**Comment by rosstuck** [comment]
Good catch, thanks!

**Comment by hannesvdvreken** [comment]
Any chance to tag a release?

**Comment by rosstuck** [comment]
@hannesvdvreken Last time we were going to, Phil warned us to expect heavy refactoring for the coming period so we held off. Do you know if that's complete now?

**Comment by hannesvdvreken** [comment]
Ah, yes, I should have thought of that. `league/container` is about to get a new major version.

Although `0.1.0` might be an appropriate version (better than using `dev-master`). Like so, version `0.2.0` can have an updated requirement on the next major version of the container package.

**Comment by rosstuck** [comment]
Fair enough. To be honest, I don't expect the slim part of the interface we use to change either way and I think our new CallableLocator released on 0.6.1 will reduce the need for all the custom locators that were necessary untl now.

I'll try to tag a release this week, thanks for the poke! :+1:

**Comment by hannesvdvreken** [comment]
It won't change much. Maybe just a change to a more high level interface will be preferred, but no other changes.

https://github.com/thephpleague/container/compare/1.x...develop#diff-20

**Pull request merged**
